//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Momento2.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Programa { get; set; }
        public System.DateTime FechaMatricula { get; set; }
        public double ValorMatricula { get; set; }
    }
}
